const route = require('express').Router()
const CartController = require('../controllers/cart')
const ProductController = require('../controllers/product')
const UserController = require('../controllers/user')
const authentication = require('../middlewares/authentication')
const authorization = require('../middlewares/authorization')

route.get('/', (req, res) => {
  res.send('Hello World!')
})
route.post('/register', UserController.register)
route.post('/login', UserController.login)
route.get('/ecomm-client/product', ProductController.showAll)
route.use(authentication)
route.get('/ecomm-client', CartController.fetchCart)
route.post('/ecomm-client', CartController.addCart)
route.patch('/ecomm-client', CartController.editCart)
route.delete('/ecomm-client', CartController.deleteCart)
route.use(authorization)
route.get('/ecommerce', ProductController.showAll)
route.get('/ecommerce/:id', ProductController.showOne)
route.post('/ecommerce', ProductController.add)
route.put('/ecommerce/:id', ProductController.edit)
route.delete('/ecommerce/:id', ProductController.deleted)

module.exports = route